<?php
$host="localhost";
$usuarioBd="root";
$passBd="xampp";
$dbBd="encuesta2012";
//numero de preguntas total en la encuesta
$numeroTotalEncuesta=99;
//nombre de la tabla donde se guardan las respuestas
$tablaEncuestas="encuestas";
//nombre del atributo title en las paginas
$title="ENCUESTA CLIMA LABORAL 2012";
//titulo de la ventana estadisticas
$titleEstadisticas="ESTADISTICAS DE LA ENCUESTA - CLIMA LABORAL 2012";
?>
