<?php
$host="localhost";
$usuarioBd="root";
$passBd="xampp";
$dbBd="encuesta2012";
//numero de preguntas total en la encuesta
$numeroTotalEncuesta=35;
//nombre de la tabla donde se guardan las respuestas
$tablaEncuestas="encuestas";
//nombre del atributo title en las paginas
$title="EVALUACION 360&deg;";
//titulo de la ventana estadisticas
$titleEstadisticas="ESTADISTICAS DE LA EVALUACION 360&deg;";
?>
